### PR TITLE
Add variable expansion to URLs for values

### PR DESCRIPTION
**Pull request by jkroepke**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by jkroepke** [comment]
Hey @jmclean-starburst, is it possible that you can checkout this and test it on your setup?

**Comment by jmclean-starburst** [comment]
getting the below
```
error loading config: no matching creation rules found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5401918]
```

**Comment by jkroepke** [comment]
Hm, it looks good in general here, because

* no errors from curl, it means fetch the file was successful.
* `panic: runtime error: invalid memory address or nil pointer dereference`
   This is expectable. helm throws a gopanic, if loading the file was not successfully.
   https://github.com/helm/helm/issues/8935

* `error loading config: no matching creation rules found`. This comes from sops maybe after fetching the content. I have no idea, why this comes. This error is expectable at encryption process, but not on the decryption process.

Set `HELM_SECRETS_DEBUG=true` help here to get deeper into this.

**Comment by jmclean-starburst** [comment]
the `lineEscaped` value is wrong...it shows the value w/ the env var in there (not substituted)

FWIW - i pass in the url string being surrounded by single quotes (ie `'`), so something like:
```
HELM_SECRETS_URL_VARIABLE_EXPANSION=true HELM_SECRETS_DEBUG=true helm template mychart ./mychart -f 'secrets://https://${GITHUB_TOKEN}@raw.githubusercontent.com/org/repo/ref/pathtofile.yml'
```

I do this because I am trying to mimic what ArgoCD passes in.

**Comment by jkroepke** [comment]
Looks like https://github.com/mozilla/sops/issues/884

**Comment by jmclean-starburst** [comment]
seems like the only time you leverage the expansion is via the below, which doesnt actually update the `$file` variable used

```

    if ! _file_exists "$file"; then
        error 'File does not exist: %s\n' "${file}"
    fi

    real_file=$(_file_get "${file}")
```
I would have expected the `real_file` to fetch from the newly created url

**Comment by jkroepke** [comment]
`_file_get` is calling `_file_http_get` and the functions eval the URL, download the file and returns the path of the temporary file which holds the content of the curl command.

Then, the temporary file path is passed to sops.

What happens, if you are using a invalid `GITHUB_TOKEN`? same error?

**Comment by jmclean-starburst** [comment]
a bad token gives the below after a curl command
```
curl: (22) The requested URL returned error: 404 
```

Then I get the:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5401918]
```

**Comment by jkroepke** [comment]
This validates that the evaluation works in general. 

Maybe we are hitting https://github.com/mozilla/sops/issues/884 here. I do a commit here which introduce a workaround for that case.

Otherwise, the encrypted yaml file from `org/repo/ref/pathtofile.yml` is strange.

**Comment by jmclean-starburst** [comment]
@jkroepke definitely seems like the issue is the sops tag above....i had a local `.sops.yaml` file with more specific rules. When I deleted it, it likely defaulted to your file which is more of a catch al, and it worked! thanks for all the work on this. we plan on using it HEAVILY ;)

**Comment by jkroepke** [comment]
Thanks for the feedback. Great to know that it works now.

> and it worked!

I would like to know, if I the empty sops.yaml file is still needed, because it worked years fine without it.

Before merging this, I still needs to write some documentation about this feature.

**Pull request merged**
