### PR TITLE
Add Gopass driver

### PR DESCRIPTION
**Pull request by treussart**

### CODE REVIEW

**Comment by jkroepke** [comment]
gopass supports yaml format directly.

this a vault like wrapper required for gopass?

**Comment by treussart** [comment]
Hi,
As far as I know, Gopass does not support the yaml format directly, you have to use summon : https://github.com/gopasspw/gopass/blob/master/docs/summon-provider.md
Indeed, it's a vault like wrapper for Gopass, I'm using Gopass as my password storage.

**Comment by jkroepke** [comment]
What about this?

https://github.com/gopasspw/gopass/blob/master/docs/features.md#directly-edit-structured-secrets-aka-yaml-support

or MIME Secrets (successor of yaml format)?

https://github.com/gopasspw/gopass/blob/master/docs/features.md#mime-secrets

Did you try that?

I guess it's might be better to have a sops like handling like the vault like handing. It will reduce a lot of shell code.

**Comment by treussart** [comment]
Hi, 
MIME secrets are not a good choice for helm secrets, I don't want to have multiple secrets in a file, just context (user, url, description, ...), no more. 
I don't like sops because I like to have my secrets centralized in a repo and not in YAML files all over the place.

**Comment by jkroepke** [comment]
Hi @treussart ,

in #63 I moved the logic to out of the vault driver. No it's possible to re-use the logic by other drivers.

Could you take a look at https://github.com/jkroepke/helm-secrets/commit/a9fbe4a7e974778e651c979f12350cf5e781f7a8 if this fits for you? It should reduce the amount of new code compared to this PR.

**Comment by treussart** [comment]
Hard to say, we would have to test with gopass and helmfile.
We are now using summon for our project : https://github.com/cyberark/summon

**Comment by jkroepke** [comment]
All right, thanks for the feedback.

**Pull request closed without merging**
