### PR TITLE
bump sops to 3.8.1

### PR DESCRIPTION
**Pull request by lucasfcnunes**
**What this PR does / why we need it**:
Bumps sops from 3.7.3 (1+ years old) to 3.8.1

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] Rebase after https://github.com/jkroepke/helm-secrets/pull/407 gets merged
- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

### CODE REVIEW

**Comment by jkroepke** [comment]
The `mdgreenwald/mozilla-sops-action` github action still [points to `mozilla/sops`](https://github.com/mdgreenwald/mozilla-sops-action/blob/main/src/run.ts). Lets hope for the best.

**Comment by lucasfcnunes** [comment]
@jkroepke
Is this caused by a missing GPG private key for D6174A02027050E59C711075B430C4E58E2BBBA3?
```
#   Failed to get the data key required to decrypt the SOPS file.
# 
#   Group 0: FAILED
#     D6174A02027050E59C711075B430C4E58E2BBBA3: FAILED
#       - | could not decrypt data key with PGP key:
#         | github.com/ProtonMail/go-crypto/openpgp error: could not
#         | load secring: open /home/runner/.gnupg/pubring.gpg: no such
#         | file or directory; GnuPG binary error: failed to decrypt
#         | sops data key with pgp: gpg: encrypted with RSA key, ID
#         | D71EE6A0B038EE0C
#         | gpg: decryption failed: No secret key
# 
#   Recovery failed because no master key was able to decrypt the file. In
#   order for SOPS to recover the file, at least one key has to be successful,
#   but none were.
```

**Comment by jkroepke** [comment]
Hm, on main everything is working fine. Seems like sops has changed some behaviors.

**Comment by lucasfcnunes** [comment]
@jkroepke, is this still relevant?

**Comment by jkroepke** [comment]
Sure, its should be still relevant.

**Review by jkroepke — APPROVED** [review]
LGTM 👍

**Pull request merged**
