### PR TITLE
Allow dot, asterisk and underscore for vault path

### PR DESCRIPTION
**Pull request by zifter**
allow path like:
secret/devops/certificates/internal.domain-with-hyphen.com#file.crt

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi @zifter 

can you extend the existing secret files and seed that covers such a vault key?

See:

* https://github.com/jkroepke/helm-secrets/blob/main/tests/assets/values/vault/seed.sh
* https://github.com/jkroepke/helm-secrets/blob/main/tests/assets/values/vault/secrets.yaml

Thanks.

**Comment by jkroepke** [comment]
Looks like keys with an star won’t work?

> !vault secret/domain#*.test-example.com

**Comment by zifter** [comment]
> Looks like keys with an star won’t work?
> 
> > !vault secret/domain#*.test-example.com

Not exactly, I suppose I have to fix regexp in test assets. I didn't expect that

**Comment by jkroepke** [comment]
Ah I see.

**Comment by zifter** [comment]
sorry, @jkroepke what's wrong with last checks run? I see that it was cancelled

**Comment by jkroepke** [comment]
> sorry, @jkroepke what's wrong with last checks run? I see that it was cancelled

idk, it just hangs for 15 minutes. I reschedule the check.

**Comment by zifter** [comment]
@jkroepke is it possible to make new release 3.8.3 ASAP? It will be really helpful. If you wish, I can make necessary preparations (based on previous releases).

**Comment by jkroepke** [comment]
Done.

**Pull request merged**
