### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by mamoit**
**What this PR does / why we need it**: Minor typo in README.md

**Which issue this PR fixes**: none

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR (**there are no significant changes**)

### CODE REVIEW

**Comment by mamoit** [comment]
Feel free to discard this MR and commit one of your own if it is somehow non-standard to the repo policies.
I just didn't want to let the typo fly under the radar.

**Comment by jkroepke** [comment]
> if it is somehow non-standard to the repo policies.

This is a standard sentences form you? Or did you find any non-standard to the repo policies?

**Comment by jkroepke** [comment]
Thanks anyway!

**Comment by mamoit** [comment]
I meant commit message standard or something else that might not have been according to your standards (since it's my first time committing to this project).
Nevermind, I was just lacking confidence :smile:

**Pull request merged**
